package wms.integration;

import java.time.LocalDateTime;
import java.util.List;

/**
 * Immutable event object representing a shipment state change in WMS.
 *
 * Published by WMS when:
 * - A shipment is packed and ready for carrier pickup (READY_FOR_PICKUP)
 * - A shipment is rejected due to QC failure or damage (CANNOT_SHIP)
 *
 * Consumed by Subsystem 6 (Transport and Logistics Management) via REST polling.
 * WMS has no knowledge of TMS — events are stored and served on demand.
 *
 * PATTERN — Observer / Event (decoupled publish-subscribe via polling)
 * SOLID — Open/Closed: new event types can be added without modifying TMS
 * GRASP — Low Coupling: TMS polls independently, WMS never calls TMS
 */
public class ShipmentReadyEvent {

    /** Unique shipment identifier — matches packing job ID from Subsystem 14 */
    private final String shipmentId;

    /** The outbound order IDs included in this shipment */
    private final List<String> orderIds;

    /** Timestamp when this event was created */
    private final LocalDateTime eventTimestamp;

    /** Total weight of all packages in kg */
    private final double totalWeightKg;

    /** Number of physical packages in the shipment */
    private final int totalPackages;

    /**
     * Barcode string generated by Subsystem 14 (Packing).
     * Format: SCM|jobId|orderId|timestamp
     */
    private final String barcode;

    /**
     * Current shipment status.
     * READY_FOR_PICKUP — packed and ready for carrier collection
     * CANNOT_SHIP      — rejected due to QC failure or damage
     */
    private final String status;

    /** Human-readable reason — populated for CANNOT_SHIP events only */
    private final String rejectionReason;

    /** Product contents of this shipment for TMS route optimization */
    private final List<ShipmentItem> contents;

    /**
     * Constructs a READY_FOR_PICKUP event (normal outbound dispatch).
     *
     * @param shipmentId     Packing job ID from Subsystem 14
     * @param orderIds       Outbound order IDs in this shipment
     * @param totalWeightKg  Total physical weight
     * @param totalPackages  Number of packages
     * @param barcode        Barcode from Subsystem 14 packing label
     * @param contents       Product line items in this shipment
     */
    public ShipmentReadyEvent(String shipmentId, List<String> orderIds,
                               double totalWeightKg, int totalPackages,
                               String barcode, List<ShipmentItem> contents) {
        this.shipmentId = shipmentId;
        this.orderIds = List.copyOf(orderIds);
        this.eventTimestamp = LocalDateTime.now();
        this.totalWeightKg = totalWeightKg;
        this.totalPackages = totalPackages;
        this.barcode = barcode;
        this.status = "READY_FOR_PICKUP";
        this.rejectionReason = null;
        this.contents = List.copyOf(contents);
    }

    /**
     * Constructs a CANNOT_SHIP event (QC failure or damage detected).
     *
     * @param shipmentId      The shipment that cannot proceed
     * @param orderIds        Order IDs affected
     * @param rejectionReason Why the shipment was rejected
     */
    public ShipmentReadyEvent(String shipmentId, List<String> orderIds,
                               String rejectionReason) {
        this.shipmentId = shipmentId;
        this.orderIds = List.copyOf(orderIds);
        this.eventTimestamp = LocalDateTime.now();
        this.totalWeightKg = 0.0;
        this.totalPackages = 0;
        this.barcode = null;
        this.status = "CANNOT_SHIP";
        this.rejectionReason = rejectionReason;
        this.contents = List.of();
    }

    // ── Getters — read-only, no setters (immutable event) ────────────────────

    public String getShipmentId()       { return shipmentId; }
    public List<String> getOrderIds()   { return orderIds; }
    public LocalDateTime getEventTimestamp() { return eventTimestamp; }
    public double getTotalWeightKg()    { return totalWeightKg; }
    public int getTotalPackages()       { return totalPackages; }
    public String getBarcode()          { return barcode; }
    public String getStatus()           { return status; }
    public String getRejectionReason()  { return rejectionReason; }
    public List<ShipmentItem> getContents() { return contents; }

    /**
     * Represents a single product line item within a shipment.
     * Used by TMS for route planning and carrier manifests.
     */
    public static class ShipmentItem {
        private final String productId;
        private final int quantity;
        private final String description;

        public ShipmentItem(String productId, int quantity, String description) {
            this.productId = productId;
            this.quantity = quantity;
            this.description = description;
        }

        public String getProductId()  { return productId; }
        public int getQuantity()      { return quantity; }
        public String getDescription() { return description; }

        @Override
        public String toString() {
            return "ShipmentItem{productId='" + productId
                    + "', quantity=" + quantity
                    + ", description='" + description + "'}";
        }
    }

    @Override
    public String toString() {
        return "ShipmentReadyEvent{"
                + "shipmentId='" + shipmentId + '\''
                + ", status='" + status + '\''
                + ", orderIds=" + orderIds
                + ", totalWeightKg=" + totalWeightKg
                + ", totalPackages=" + totalPackages
                + ", barcode='" + barcode + '\''
                + ", eventTimestamp=" + eventTimestamp
                + ", rejectionReason='" + rejectionReason + '\''
                + '}';
    }
}
